---
### Ansible hosts inventory

# Group "all"
all:
    hosts:
      # individual hosts and vars
      demo-host:
        ansible_host: 127.0.0.1
        ansible_user: "{{ lookup('env', 'USER') }}"
    vars:
      # variables used for all hosts
      ansible_python_interpreter: /usr/bin/python3
    children:
      project_hosts:
        hosts:
          demo-host
      project_secrets:
        children:
          project_hosts
